name: CI

on:
  push:
    branches: [master]
    paths_ignore: ["**.md"]
  pull_request:
    paths_ignore: ["**.md"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test asdf plugin
      uses: asdf-vm/actions/plugin-test@v1
      with:
        command: stern --version
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Shellcheck
      run: |
        which shellcheck
        shellcheck -V
        shellcheck bin/*
